"""create_citizen_tables

Revision ID: 209275ce21db
Revises: a9b0c9fe190e
Create Date: 2025-06-12 09:13:43.042580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209275ce21db'
down_revision: Union[str, None] = 'a9b0c9fe190e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cccd', sa.String(length=12), nullable=True),
    sa.Column('ho_ten', sa.String(length=100), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sa.String(length=10), nullable=True),
    sa.Column('noi_thuong_tru', sa.Text(), nullable=True),
    sa.Column('noi_o_hien_tai', sa.Text(), nullable=True),
    sa.Column('noi_tam_tru', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_cccd'), 'citizens', ['cccd'], unique=True)
    op.create_index(op.f('ix_citizens_id'), 'citizens', ['id'], unique=False)
    op.create_table('citizen_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_details', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_verifications_id'), 'citizen_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_verifications_id'), table_name='citizen_verifications')
    op.drop_table('citizen_verifications')
    op.drop_index(op.f('ix_citizens_id'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_cccd'), table_name='citizens')
    op.drop_table('citizens')
    # ### end Alembic commands ###
