"""Add ma_ho_so to Case

Revision ID: a9b0c9fe190e
Revises: 68f8ba80d99f
Create Date: 2025-06-11 14:09:54.193645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b0c9fe190e'
down_revision: Union[str, None] = '68f8ba80d99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('ma_ho_so', sa.String(), nullable=True))
    op.create_index(op.f('ix_cases_ma_ho_so'), 'cases', ['ma_ho_so'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_ma_ho_so'), table_name='cases')
    op.drop_column('cases', 'ma_ho_so')
    # ### end Alembic commands ###
